### PR TITLE
BUG: common: fix cholesky upper decomp for complex dtypes

### PR DESCRIPTION
**Pull request by lucascolley**
Closes gh-54.

cc @asmeurer

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @lucascolley! I verified the change on your NumPy PR, and this matches that one. In it goes.

**Comment by rgommers** [comment]
Actually, let me re-run CI since a PyTorch job was red and I couldn't see the CI log anymore.

**Comment by lucascolley** [comment]
thanks Ralf. I wonder whether any changes are needed to `array-api-tests` since this wasn't caught initially?

**Comment by rgommers** [comment]
> I wonder whether any changes are needed to `array-api-tests` since this wasn't caught initially?

I checked quickly, and yes indeed - `upper` is tested, but only with real-valued dtypes (via `floating_dtypes` from hypothesis). I guess the fix is to use `complex_dtypes` from https://hypothesis.readthedocs.io/en/latest/_modules/hypothesis/extra/array_api.html. Are you interested to follow up on that?

**Comment by rgommers** [comment]
Several failures due to `fft` testing mainly, I assume because new tests were added in the test suite and not yet here.

All the `linalg.cholesky` tests passed, so I'll go ahead and merge this.

**Comment by lucascolley** [comment]
> Are you interested to follow up on that?

I had a look but I'm not sure how to fix. Will open an issue instead.

**Pull request merged**
